before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: ZsksmHi2mCaGaHZC4zux/r2SgxQa0Nl4F/vlz6oBcbaBi7GbW0ZXmfpMBeRxdwTazVQnxp+8Rqjr+LTrexhsTUY3Y0GfStcALNNUZcjKOievSKtbf4qkcMABRD7TqtekycF70UIHEvwwskcaVPk1bWlkFjl1FO8T6FUquCTDE3PR5UJ+P/yyguUE6C6u0LyN71uUHPaUvA/1epr3h9vrifNjc1XBQMWDPUdOZ6FeSxZcYCQBz05jRpLmJNKKRbIufgr35hMz+denlPGXd80mvxvv90PsokJJfYvYpFU0sFfQT+YXkE3XqeaGrYCgY3bDhORMCis/vVjiMZX3KnxYxmLyZgntrxPNT9OClADyyhBRXHmCueUN26rRizcVPJV3J3CT6ABRVlUa48hwMukXl37IfK+jLs6j1MIEunc3syDTHaCa5tM9NLKwkr70H5l4owu9USADGJifGjsqOXgfl7wY5MjurcdvQlpraM+jBOYmsgojlXbT0yPWtLwjffTu/dxhhiKwq8yRfRNEjjuZ9L5/DlbN/DjvH5g/mrWEF+3J70HFQwCu4m5HoRdBY57dZZzoZqKbje3uEMWZtxp6cAIFN/+GhZA+g5iaIWoUyNPw7AaPF4TF7i/opnoPguQDTD3VKK5ROI8lqO7CO32pxOs5ekq3Q63dgT3ljPNqF1o= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
